// ════════════════════════════════════════
// Book 57 · ষাট ক্রেডিটের রিহলা — Doors 19–23 (বর্ষ-পঞ্চয়্য, 2026→2031)
// ════════════════════════════════════════

// ── দরজা ১৯ · প্রথম বছরের কাফেলা (Year 1: Fall 2026 – Summer 2027) ──────────────────
doors.push({
  num: 19,
  icon: "🌅",
  color: "#7dd3fc",
  name: "প্রথম বছরের কাফেলা",
  subtitle: "The First-Year Caravan — Settling the Rhythm (Fall 2026 – Summer 2027)",
  tech: "Program Onboarding · First Residency · Work-Study Rhythm · IS 5203 + IS 5403 + IS 5213 + BAN 5013 (12 credits)",
  spirit: "بِسْمِ اللَّهِ مَجْرَاهَا وَمُرْسَاهَا — 'আল্লাহর নামেই এর চলা-থামা' (কুরআন ১১:৪১, নূহ-এর নৌকা-যাত্রা); প্রতিটি বড় যাত্রার প্রথম বছর = ছন্দ বসানো",
  secret: "প্রথম বছরের কাজ কোর্স শেষ করা নয় — ছন্দ তৈরি করা: কখন পড়বে, কখন কাজ, কখন পরিবার, কখন ঘুম; ছন্দ দাঁড়ালে বাকি চার বছর স্বয়ংক্রিয়।",
  recall: {
    q: "প্রথম বছরের দুই মূল লক্ষ্য কী?",
    qen: "The two core goals of Year 1?",
    a: "(১) ১২ ক্রেডিট শেষ (IS 5203, IS 5403, IS 5213, BAN 5013) — নিরাপদ ২-কোর্স/টার্ম ছন্দে; (২) সাপ্তাহিক ব্লক-ক্যালেন্ডার স্থির করা (রাতের ৩ ব্লক + শনিবার) যা পরীক্ষার সপ্তাহেও ভাঙবে না।",
    aen: "(1) Finish 12 credits (IS 5203, IS 5403, IS 5213, BAN 5013) at a safe 2-course pace; (2) fix a weekly block-calendar (3 evening blocks + Saturday) that survives exam weeks."
  },
  story: `<p class="scene-setting">আগস্ট ২০২৬। কাফেলা ছেড়েছে — এখনো মরুর প্রথম বালিয়াড়ি। এই দরজার মাস্টার <strong>কাফেলা-সংগঠক সালেহ</strong> — কাঁধে চামড়ার খাতা, যেখানে প্রতিটি উটের গতি, প্রতিটি সরাইয়ের দূরত্ব লেখা। তিনি বলেন, "দলিলে দেখেছি — কাফেলা কখনো ঝড়ে মরে না, মরে <strong>ভুল ছন্দে</strong>: প্রথম দিন দৌড়ো, তৃতীয় দিনে ভেঙে পড়ো। তাই প্রথম বছরের একমাত্র কাজ: তোমার ছন্দ খুঁজে বের করা। তুমি একাই নয় — সপ্তাহে ৫ দিন তোমার LedgerPilot-Ipractus-কারিগরি চলবে, তারপরও প্রতি সপ্তাহে <strong>তিন রাতের ব্লক + শনিবারের মহাব্লক</strong> — এই চার আসনেই বসবে তোমার DIT।" Fall 2026-এ প্রথম দুই দরজা: পথরক্ষকের নেটওয়ার্ক (IS 5203) আর দুর্গ-প্রহরীর সিকিউরিটি (IS 5403) — তোমার DevOps-হাতের কাছেই। Spring 2027-এ স্রোত-গণনাকারীর ডেটা (IS 5213) আর যন্ত্রশালের টুলস (BAN 5013)। মাঝে প্রথম <strong>residency</strong> — ক্যাম্পাসে সহপাঠী-প্রফেসরদের সাথে মুখোমুখি: hybrid-ছাত্রের একমাত্র সুযোগ মানুষজনকে 'আসল' করে নেওয়ার।</p>
<p class="scene-setting en">August 2026. The caravan has left — still the first dunes. This door's master is <strong>Salih the Caravan-Organizer</strong> — a leather ledger on his shoulder recording every camel's pace, every waypoint's distance. He says, "My ledger shows — caravans never die in storms; they die of <strong>wrong rhythm</strong>: sprint on day one, collapse by day three. So Year 1 has a single job: find your rhythm. You are not alone — five days a week your LedgerPilot-Ipractus craft continues, yet every week <strong>three evening blocks + Saturday's grand block</strong> — in these four seats sits your DIT." Fall 2026 opens the first two doors: the Waykeeper's networks (IS 5203) and the Fortress Guard's security (IS 5403) — both within reach of your DevOps hands. Spring 2027 brings the Flood-Counter's data (IS 5213) and the Toolsmith's analytics (BAN 5013). Between them, your first <strong>residency</strong> — meeting classmates and professors face to face: the hybrid student's one chance to make the people 'real.'</p>
<div class="dialogue"><strong>তুমি:</strong> সালেহ-সাহেব, full-time চাকরি + দুই কোর্স — সম্ভব তো?<br><strong>কাফেলা-সংগঠক সালেহ:</strong> সম্ভব, শর্ত তিনটা। <strong>এক:</strong> সনিবেশ-বিদ্যা — কোর্সের সব ডেডলাইন শুরুতেই ক্যালেন্ডারে (assignment, পরীক্ষা, residency-তারিখ); চাকরির মিটিং-ক্যালেন্ডারের পাশে একই ক্যালেন্ডারে। <strong>দুই:</strong> আমানত-ঘোষণা — পরিবার ও দলকে জানাও 'মঙ্গল-বৃহস্পতি রাত আর শনি সকাল আমার পড়ার'; লুকালে দুই দিকই ক্ষতি। <strong>তিন:</strong> পতন-পরিকল্পনা — এক সপ্তাহ পিছিয়ে গেলে কী করবে তা আগেই লিখে রাখো (কোন assignment ছোট, কোনটা বড়); পতন লজ্জা নয়, পতন-পরিকল্পনাহীনতাই বিপদ।<br><strong>তুমি:</strong> আর residency?<br><strong>কাফেলা-সংগঠক সালেহ:</strong> সেটা তোমার মিলনমেলা — যাওয়ার আগে ৩ জন প্রফেসরের নাম মুখস্থ, ৫ জন সহপাঠীর সাথে কথা বলা, LinkedIn-যোগাযোগ। Hybrid-প্রোগ্রামের সবচেয়ে বড় ঝুঁকি একাকিত্ব; residency তার প্রতিষেধক — ফেলে আসা যাবে না।</div>
<div class="dialogue en"><strong>You:</strong> Salih, full-time job + two courses — is it possible?<br><strong>Salih the Organizer:</strong> Possible, on three conditions. <strong>One:</strong> total calendaring — every deadline into one calendar at term start (assignments, exams, residency dates) beside your work meetings. <strong>Two:</strong> declaration of trust — tell family and team 'Tuesday-Thursday evenings and Saturday mornings are my study'; hiding harms both sides. <strong>Three:</strong> a fall-plan — write in advance what you'll do when a week slips (which assignment is small, which large); falling is not shame, having no fall-plan is the danger.<br><strong>You:</strong> And residency?<br><strong>Salih:</strong> That is your fair — before going, memorize three professors' names, talk to five classmates, connect on LinkedIn. Hybrid programs' greatest risk is loneliness; residency is its antidote — never skip it.</div>
<table class="kv-table">
<tr><th>প্রথম বছরের ঋতু</th><th>কাজ</th><th>ক্রেডিট-জমা</th></tr>
<tr><td class="hl">Fall 2026</td><td>IS 5203 (D2) + IS 5403 (D3) + প্রথম residency + ক্যালেন্ডার-স্থাপন</td><td>৬</td></tr>
<tr><td class="hl">Spring 2027</td><td>IS 5213 (D4) + BAN 5013 (D5) + LedgerPilot-ডেটায় প্র্যাকটিস</td><td>১২</td></tr>
<tr><td class="hl">Summer 2027</td><td>বিশ্রাম বা হালকা কিছু — ছন্দ যাচাই, গ্রহণ-ক্ষমতা পুনরুদ্ধার</td><td>১২</td></tr>
</table>
<div class="callout warn"><span class="co-icon">⚠️</span><div><strong>প্রথম-বছরের ফাঁদ:</strong> (১) প্রথম সেমিস্টারেই ৩-৪ কোর্স নেওয়ার উৎসাহ — hybrid+চাকরিতে ২-ই সঠিক গতি; (২) চুপচাপ হারিয়ে যাওয়া — দুই সপ্তাহ মিস করলে advisor-কে নিজেই খোঁজ দাও, লজ্জা নয়; (৩) residency বাদ দেওয়া — শুরুতেই ত্যাগ করা সস্তায় মনে হয়, শেষে একাকিত্ব সুদে দেনা নেয়।</div></div>
<div class="callout tip"><span class="co-icon">🔗</span><div><strong>রিহলা-সেতু:</strong> দরজা ২-৫-এর প্রতিটি senior-গাইড এই বছরই কাজে লাগবে; আর তোমার লাইব্রেরির Book 32 (Brain Mechanic — অভ্যাস-ব্যবস্থা) রাতের ব্লক-ছন্দ স্থির করার হাতিয়ার।</div></div>
<div class="verse">بِسْمِ اللَّهِ مَجْرَاهَا وَمُرْسَاهَا ۚ إِنَّ رَبِّي لَغَفُورٌ رَّحِيمٌ — "আল্লাহর নামেই এর চলা ও থামা।" (কুরআন ১১:৪১) — যাত্রার প্রথম কথা নাম, শেষ কথা ক্ষমা; মাঝে ছন্দ।</div>
<div class="secret-box">🌅 প্রথম বছর = ছন্দের বছর: ২ কোর্স/টার্ম × ২ টার্ম = ১২ ক্রেডিট, এক ক্যালেন্ডার, এক ঘোষণা, এক পতন-পরিকল্পনা, এক residency। দৌড় নয় — থিতু।</div>`,
  senior: {
    title: "Year 1 জীবন্ত চেকলিস্ট (Fall 2026 – Summer 2027)",
    body: `<p><strong>শুরুর ৩০ দিনে:</strong> কোর্স-প্ল্যাটফর্ম (Canvas/মাইলস্টোন) চিনে নাও; সব ডেডলাইন এক ক্যালেন্ডারে; advisor-এর সাথে পরিচিতি-মিটিং; সাপ্তাহিক ব্লক পরিবারকে জানাও। <strong>প্রতি সপ্তাহে:</strong> ৩ রাত + শনি-ব্লক অলঙ্ঘনীয়; রবিবার ১৫ মিনিটের পর্যালোচনা — আগামী সপ্তাহের ডেডলাইন কী। <strong>শেষে:</strong> ১২ ক্রেডিট + অন্তত ৫টি বাস্তব সহপাঠী-সম্পর্ক + একটি স্থায়ী সাপ্তাহিক ছন্দ। <strong>সংকট-সংকেত:</strong> টানা দুই সপ্তাহ ব্লক-মিস → advisor + পরিবারের সাথে খোলা কথা; কোর্স ড্রপের সিদ্ধান্ত লজ্জার নয়, হিসাবের।</p>`
  }
});

// ── দরজা ২০ · মাঝরাস্তার মিলন (Year 2: Fall 2027 – Summer 2028) ──────────────────
doors.push({
  num: 20,
  icon: "🧭",
  color: "#5eead4",
  name: "মাঝরাস্তার মিলন",
  subtitle: "The Midway Meeting — Management & Momentum (Fall 2027 – Summer 2028)",
  tech: "DIT 7043 + DIT 7053 + DIT 7063 + DIT 7073 (12 credits) · Midpoint Checkpoint · Status Vigilance in an I-20 Year",
  spirit: "وَإِذَا حَكَمْتُم بَيْنَ النَّاسِ أَن تَحْكُمُوا بِالْعَدْلِ — 'মানুষের মধ্যে বিচার করলে ন্যায়ে করো' (কুরআন ৪:৫৮); নেতৃত্ব-বছরের নৈতিক মেরুদণ্ড",
  secret: "দ্বিতীয় বছর কোর্সের বছর নয় — দৃষ্টিভঙ্গির বছর: তোমার হাতের কারিগরি এখন ওজিরের টেবিলে (DIT 7043) বসে; ইঞ্জিনিয়ার-চোখ ম্যানেজার-চোখে যোগ করো — এই দ্বৈত-দৃষ্টিই DIT-র আসল ডিগ্রি।",
  recall: {
    q: "কোর-পর্বের মাঝপথে কোন ৪টি কোর্স, আর কেন এদের বলে 'দৃষ্টি-জোড়া'?",
    qen: "Which 4 courses fill the core decade's midpoint, and why call them the 'vision pair'?",
    a: "Fall 2027: DIT 7043 (IT Management — ওজিরের দরবার) + DIT 7053 (Procurement — ক্রয়-সরাই); Spring 2028: DIT 7063 (Project Mgmt — কাফেলার নায়ক) + DIT 7073 (Innovation — আবিষ্কারের বাজার)। কারিগরি-গভীরতা থেকে সংগঠন-উচ্চতায় উঠার সিঁড়ি — তাই দৃষ্টি-জোড়া।",
    aen: "Fall 2027: DIT 7043 (IT Management) + DIT 7053 (Procurement); Spring 2028: DIT 7063 (Project Mgmt) + DIT 7073 (Innovation). The stair from technical depth to organizational height — hence the vision pair."
  },
  story: `<p class="scene-setting">২০২৭-এর শরৎ। কাফেলা এখন মরুর মাঝ-মহাদেশে — পেছনে ১২ ক্রেডিট, সামনে ৪৮। এই দরজার মাস্টার <strong>দো-ভাষী দিকনির্ণেতা জুবায়ের</strong> — এক চোখে দূরবিন, অন্য চোখে খালি মানচিত্র; বলেন, "মাঝপথেই কাফেলা ঠিক করে সে কোথায় যাচ্ছে। তোমার চার নতুন স্টেশন আর কারিগরি নয় — <strong>নেতৃত্বের</strong>: ওজিরের দরবারে বসে শিখবে প্রযুক্তি-সিদ্ধান্ত সংগঠনের ভাষায় অনুবাদ করতে (DIT 7043), ক্রয়-সরাইয়ে শিখবে চুক্তি-আমানতের হিসাব (DIT 7053), কাফেলার নায়কের কাছে সময়-সীমা-ঝুঁকির ব্যবস্থাপনা (DIT 7063), আর বাজারে উদ্ভাবনকে মূল্যে রূপান্তর (DIT 7073)। Ipractus-এ তুমি যা করছ — টিম-লিড, ক্লায়েন্ট-কথা, ডেলিভারি-চাপ — প্রতিটি কোর্সের জীবন্ত ল্যাব।" এই বছরটি আরেক কারণে সতর্ক: Spring 2028 তোমার <strong>I-20-এর শেষ-প্রান্তিক বছর</strong> — তাই প্রতিটি এনরোলমেন্ট-সিদ্ধান্ত advisor-এর সাথে লিখিত-যাচাই করা নিয়ম।</p>
<p class="scene-setting en">Autumn 2027. The caravan is mid-continent — 12 credits behind, 48 ahead. This door's master is <strong>Zubayr the Bilingual Guide</strong> — a telescope over one eye, a blank map over the other; he says, "It is at the midpoint that a caravan decides where it is truly going. Your four new stations are no longer technical — they are <strong>leadership</strong>: at the vizier's court learn to translate technology decisions into the organization's language (DIT 7043), at the procurement inn learn the arithmetic of contracts and trust (DIT 7053), from the caravan captain learn time-scope-risk management (DIT 7063), and at the market learn to turn innovation into value (DIT 7073). What you already do at Ipractus — team-lead, client-talk, delivery-pressure — is each course's living lab." This year carries one more vigilance: Spring 2028 is your <strong>I-20's final-stretch year</strong> — so every enrollment decision gets verified in writing with your advisor.</p>
<div class="dialogue"><strong>তুমি:</strong> জুবায়ের-সাহেব, কারিগরি-মানুষ হিসেবে ম্যানেজমেন্ট-কোর্সে মন বসে না অনেক সময়...<br><strong>দিকনির্ণেতা জুবায়ের:</strong> কারণ তোমরা ভুল জায়গায় খোঁজো। ওজিরের দরবারে যাও টেক্সটবুক পড়তে নয় — নিজের কোম্পানির টেবিলে ফেরত যাও। প্রতিটি মডেলের প্রশ্ন করো: 'আমার Ipractus-এ গত মাসের সেই সমস্যাটা এই কাঠামোয় ধরা পড়ত?' TCO শেখো ক্রয়-সরাই থেকে, কিন্তু হিসাব করো তোমার নিজের সার্ভার-বিলের ওপর। তখন কোর্স আর 'সাধারণ তত্ত্ব' নয় — তোমার কাজের দাঁড়িপাল্লা।<br><strong>তুমি:</strong> আর স্ট্যাটাস-সতর্কতাটা?<br><strong>দিকনির্ণেতা জুবায়ের:</strong> সোনার নিয়ম: <strong>সবকিছু লিখিত</strong>। Advisor-মিটিংয়ের পর ইমেইল-সারাংশ ('যেমনটি আলোচনা হলো...'), এনরোলমেন্ট-প্ল্যানের কপি নিজের কাছে, DSO-যোগাযোগ ফাইলভুক্ত। মৌখিক স্মৃতি মরু-বাতাসে উড়ে যায়; লিখিত দলিল তাঁবুর খুঁটি।</div>
<div class="dialogue en"><strong>You:</strong> Zubayr, as a technical person my mind often resists management courses...<br><strong>Zubayr the Guide:</strong> Because you search in the wrong place. Don't go to the vizier's court to read textbooks — return to your own company's table. Ask of every model: 'Would last month's Ipractus problem show up in this frame?' Learn TCO at the procurement inn, but compute it on your own server bill. Then the course is no longer 'general theory' — it is your work's weighing scale.<br><strong>You:</strong> And the status vigilance?<br><strong>Zubayr:</strong> Golden rule: <strong>everything in writing</strong>. After each advisor meeting an email summary ('as discussed...'), a copy of the enrollment plan in your own files, DSO communications archived. Verbal memory evaporates in desert wind; written documents are tent-poles.</div>
<table class="kv-table">
<tr><th>দ্বিতীয় বছরের ঋতু</th><th>কাজ</th><th>ক্রেডিট-জমা</th></tr>
<tr><td class="hl">Fall 2027</td><td>DIT 7043 (D6) + DIT 7053 (D7) — 'দরবার-জোড়া'; নিজের কোম্পানির কেস-স্টাডি খাতা শুরু</td><td>১৮</td></tr>
<tr><td class="hl">Spring 2028</td><td>DIT 7063 (D8) + DIT 7073 (D9) — 'নায়ক-বাজার জোড়া'; স্ট্যাটাস-নথি ডসিয়ার আপডেট</td><td>২৪</td></tr>
<tr><td class="hl">Summer 2028</td><td>ছন্দ-রক্ষা + সামনের বছরের পূর্ব-প্রস্তুতি (Python-ঝুলি মেলো)</td><td>২৪</td></tr>
</table>
<div class="callout warn"><span class="co-icon">⚠️</span><div><strong>দ্বিতীয়-বছরের ফাঁদ:</strong> (১) 'ম্যানেজমেন্ট = সহজ কোর্স' ভেবে হালকা নেওয়া — GPA-এর সবচেয়ে বড় গর্ত এখানেই; (২) কাজের ব্যস্ততায় residency/অ্যাসাইনমেন্ট ফাঁকি — দ্বৈত-জীবনের সময় এখনই সবচেয়ে টানটান, পতন-পরিকল্পনা হালনাগাদ করো; (৩) স্ট্যাটাস-প্রশ্নে 'পরে দেখব' — I-20-বছরে প্রতিটি টার্মের এনরোলমেন্ট আগেই লিখিত-নিশ্চিত।</div></div>
<div class="callout tip"><span class="co-icon">🔗</span><div><strong>রিহলা-সেতু:</strong> D6-D9 দরজাগুলোর senior-গাইড এই বছরের পাঠ্য; Book 23 (Irreplaceable Craftsman — প্রোডাক্ট-দৃষ্টি) আর Book 4 (City Builder — সিস্টেম-চিন্তা) ওজিরের দরবারে তোমার পেছনের দুই প্রহরী।</div></div>
<div class="verse">وَلَا تَنقُصُوا الْمِكْيَالَ وَالْمِيزَانَ — "দাঁড়ি ও পাল্লা কম কোরো না।" (কুরআন ১১:৮৪) — নেতৃত্বের প্রথম কাজ ন্যায়ের মাপে মাপা।</div>
<div class="secret-box">🧭 দ্বিতীয় বছর = দৃষ্টি-বছর: দরবার-জোড়া + নায়ক-বাজার জোড়া = ২৪ ক্রেডিট; প্রতিটি তত্ত্ব নিজের কোম্পানির টেবিলে পরীক্ষা করো, প্রতিটি স্ট্যাটাস-সিদ্ধান্ত লিখিতে বাঁধো।</div>`,
  senior: {
    title: "Year 2 জীবন্ত চেকলিস্ট (Fall 2027 – Summer 2028)",
    body: `<p><strong>শুরুতে:</strong> 'আমার কোম্পানির কেস-খাতা' খোলো — প্রতিটি কোর্স-মডেল নিজের বাস্তব ঘটনায় মেলানোর অভ্যাস; advisor-সাথে স্ট্যাটাস-ডসিয়ার শেয়ার। <strong>মাঝে:</strong> প্রতি টার্ম শেষে ছন্দ-নিরীক্ষা (ঘুম? পরিবার? কোর্স-মান?) — তিনটার একটা ভাঙলে পরের টার্মের লোড কমাও। <strong>শেষে:</strong> ২৪ ক্রেডিট + একটি পূর্ণ কেস-খাতা + স্ট্যাটাস-নথির সুশৃঙ্খল ডসিয়ার। <strong>সংকট-সংকেত:</strong> কোর্স-কাজ দুই-ই গুরুত্বহীন লাগা → বার্নআউটের প্রথম ধোঁয়া; এক সপ্তাহ সম্পূর্ণ ছুটি + advisor-কথা।</p>`
  }
});
// ── দরজা ২১ · দিক-বদলের দরজা (Year 3: Fall 2028 – Summer 2029) ──────────────────
doors.push({
  num: 21,
  icon: "🔭",
  color: "#7dd3fc",
  name: "দিক-বদলের দরজা",
  subtitle: "The Turning Door — Cores End, Research Begins (Fall 2028 – Summer 2029)",
  tech: "DIT 7083 (Python) + RSH 7093 (Statistics) + RSH 8003 (Quant) + RSH 8013 (Qual) (12 credits) · Committee Formation",
  spirit: "فَاقْصُصِ الْقَصَصَ لَعَلَّهُمْ يَتَفَكَّرُونَ — 'গল্প বলো, যেন তারা চিন্তা করে' (কুরআন ৭:১৭৬); গবেষণা-মোড়ের বছরের আহ্বান — শোনা নয়, ভাবা",
  secret: "তৃতীয় বছরের মোড়কে মনে রেখো: কোর-পর্ব শেষ, কিন্তু আসল ঘটনা হলো <strong>প্রশ্ন-মালিকানার হস্তান্তর</strong> — এতদিন প্রফেসর প্রশ্ন দিতেন, এখন থেকে প্রশ্ন তোমার; এই উল্টে দেওয়াই ডক্টরাল-যাত্রার প্রকৃত সূচনা।",
  recall: {
    q: "Year 3-এ কোন ৪টি কোর্স, আর 'প্রশ্ন-হস্তান্তর' বলতে কী?",
    qen: "Which 4 courses in Year 3, and what is the 'question handover'?",
    a: "Fall 2028: DIT 7083 (Python — তরুণ কারিগরের কর্মশালা) + RSH 7093 (Statistics — পরিসংখ্যানের দুর্গ); Spring 2029: RSH 8003 (Quant — সংখ্যার মিনার) + RSH 8013 (Qual — মুহাদ্দিসের চায়ের দোকান)। প্রশ্ন-হস্তান্তর: কোর্স-জগতে প্রশ্ন সিলেবাস থেকে আসে; গবেষণা-জগতে প্রশ্ন তোমার নিজের পর্যবেক্ষণ থেকে — Year 3 তার সন্ধিক্ষণ।",
    aen: "Fall 2028: DIT 7083 (Python workshop) + RSH 7093 (Statistics fortress); Spring 2029: RSH 8003 (Quant minaret) + RSH 8013 (Qual tea-house). Question handover: in coursework the question comes from the syllabus; in research it comes from your own observation — Year 3 is that hinge."
  },
  story: `<p class="scene-setting">২০২৮-এর শরৎ। পেছনে ২৪ ক্রেডিট, এবং প্রথমবার কাফেলার সামনের পথ দুই-ভাগ: বাম হাতে শেষ দুই কোর-স্টেশন, ডান হাতে রিসার্চ-মিনারের সিঁড়ি। এই দরজার মাস্টার <strong>সন্ধিক্ষণ-পাহারাদার আয়েশা</strong> — মরুতে যে নারী সূর্যোদয়-সূর্যাস্তের ঠিক মাঝের মুহূর্তটা চিনে বলে দেন কাফেলা কোন পথ নেবে। তিনি বলেন, "আমি বিশ বছর ধরে এই মোড়ে দাঁড়িয়ে আছি। কাফেলা যে দিক বদলায় জলের কারণে নয় — <strong>চোখ বদলায় বলে</strong>: এতদিন তুমি উত্তর-সংগ্রাহক ছিলে, আজ থেকে প্রশ্ন-স্রষ্টা। শেষ দুই কোর শেষ করো (Python-কর্মশালা, পরিসংখ্যানের দুর্গ), কিন্তু প্রতিটি অ্যাসাইনমেন্টে একটা করে নিজের প্রশ্ন লুকিয়ে রাখো — সেগুলোই পরে ডিসার্টেশনের বীজ। আর Spring-এ যখন মিনারের (RSH 8003) ও চায়ের দোকানের (RSH 8013) দরজায় পৌঁছাবে, তখন থেকে শুরু হয় <strong>কমিটি-খোঁজ</strong>: কোন প্রফেসর তোমার জগতের মানুষ, কার লেখা তোমার প্রশ্নের পাশে দাঁড়ায়।"</p>
<p class="scene-setting en">Autumn 2028. 24 credits behind, and for the first time the road forks: the last two core stations on the left, the research minaret's stairway on the right. This door's master is <strong>Ayesha the Threshold-Keeper</strong> — the woman of the desert who reads the exact moment between sunrise and sunset and tells the caravan which path to take. She says, "I have stood at this bend for twenty years. Caravans turn not because the water changes — <strong>but because the eyes change</strong>: until now you were a collector of answers; from today, a maker of questions. Finish the last two cores (the Python workshop, the statistics fortress), but hide one question of your own inside every assignment — those will become the seeds of your dissertation. And when you reach the minaret (RSH 8003) and the tea-house (RSH 8013) in Spring, the <strong>committee-search</strong> begins: which professor is a person of your world, whose writing stands beside your question."</p>
<div class="dialogue"><strong>তুমি:</strong> আয়েশা-আপা, কমিটি কীভাবে বুঝবো কে ঠিক?<br><strong>সন্ধিক্ষণ-পাহারাদার আয়েশা:</strong> তিন চোখে দেখো। <strong>এক, লেখার চোখ:</strong> গত দুই বছরের কোর্স-পেপারগুলোর যে নাম বারবার এসেছে, যার রেফারেন্স তুমি নিজে থেকেই খুঁজে পড়েছ — সেই প্রফেসর। <strong>দুই, কথার চোখ:</strong> residency-তে বা office-hour-এ তার সাথে ১৫ মিনিট কথা বলো — তোমার এক-লাইনের প্রশ্ন শুনে সে যদি <em>আরও প্রশ্ন</em> ফেরত দেয়, লক্ষণ ভালো; শুধু 'খুব ভালো আইডিয়া' বললে সাবধান। <strong>তিন, ছাত্রের চোখ:</strong> তার আগের ছাত্রদের খোঁজ নাও — কেমন গাইড ছিলেন, কত দ্রুত ফিডব্যাক দিতেন। কমিটি এক দিনে হয় না; এই বছরটাই হলো কমিটি-বছর।<br><strong>তুমি:</strong> আর চাকরি + গবেষণা একসাথে?<br><strong>আয়েশা:</strong> এখন থেকে তোমার সাপ্তাহিক শনি-ব্লকের নতুন নাম: <strong>'প্রশ্ন-বাগান'</strong> — অর্ধেক কোর্স-কাজ, অর্ধেক নিজের প্রশ্ন-চাষ (সাহিত্য-পাঠ, খসড়া-নোট)। LedgerPilot-এর ডেটা-সমস্যাগুলো এখন তোমার গবেষণা-ভাণ্ডার; প্রতিটি প্রোডাক্ট-সমস্যা সম্ভাব্য রিসার্চ-কোশ্চেন।</div>
<div class="dialogue en"><strong>You:</strong> Ayesha, how do I know who fits the committee?<br><strong>Ayesha:</strong> Look with three eyes. <strong>First, the eye of writing:</strong> the professor whose name appeared again and again in your course papers, whose references you sought out yourself — that one. <strong>Second, the eye of talk:</strong> at residency or office-hour, speak fifteen minutes — if your one-line question gets <em>more questions</em> back, the sign is good; if only 'very nice idea,' be careful. <strong>Third, the eye of students:</strong> seek out their former students — what kind of guide, how fast the feedback. Committees aren't built in a day; this is the committee-year.<br><strong>You:</strong> And job + research together?<br><strong>Ayesha:</strong> From now on your Saturday block gets a new name: <strong>the question-garden</strong> — half coursework, half cultivating your own questions (reading literature, draft notes). LedgerPilot's data problems are now your research treasury; every product problem a possible research question.</div>
<table class="kv-table">
<tr><th>তৃতীয় বছরের ঋতু</th><th>কাজ</th><th>ক্রেডিট-জমা</th></tr>
<tr><td class="hl">Fall 2028</td><td>DIT 7083 (D10) + RSH 7093 (D11) — শেষ কোর-জোড়া; প্রতি অ্যাসাইনমেন্টে নিজের-প্রশ্ন লুকানো</td><td>৩০</td></tr>
<tr><td class="hl">Spring 2029</td><td>RSH 8003 (D13) + RSH 8013 (D14) — রিসার্চ-পঞ্চয় শুরু; কমিটি-খোঁজ শুরু</td><td>৩৬</td></tr>
</table>
<div class="callout warn"><span class="co-icon">⚠️</span><div><strong>তৃতীয়-বছরের ফাঁদ:</strong> (১) কোর-মানসিকতায় রিসার্চ-কোর্স পড়া — RSH-কোর্সও সিলেবাস-চালিত, কিন্তু তাদের আসল ফল প্রশ্ন-চোখ; শুধু গ্রেড নিয়ে উঠলে বছরটা নষ্ট; (২) কমিটি শেষ মুহূর্তে জোড়া — Year 4-এর প্রস্তাবনার আগে কমিটি দাঁড়ানো না থাকলে proposal-প্রক্রিয়া আটকে যায়; (৩) নিজের প্রশ্নকে 'চাকরির কাজ, গবেষণা নয়' ভেবে ফেলে রাখা — DIT-র সৌন্দর্য ঠিক এখানেই: কাজের সমস্যাই গবেষণার উপাদান।</div></div>
<div class="callout tip"><span class="co-icon">🔗</span><div><strong>রিহলা-সেতু:</strong> দরজা ১০-১১ (Python, Statistics) এই বছরের শরৎ-পাঠ; দরজা ১৩-১৪ (Quant, Qual) বসন্ত-পাঠ; আর Book 27 (Deep Work Sanctuary) প্রশ্ন-বাগানের সময়-রক্ষক।</div></div>
<div class="verse">وَقُل رَّبِّ زِدْنِي عِلْمًا — "বলো, হে আমার রব, আমার জ্ঞান বাড়াও।" (কুরআন ২০:১১৪) — উত্তর জমানোর নয়, জ্ঞান-ক্ষুধা বাড়ানোর দোয়া; গবেষণা-মোড়ের প্রার্থনা।</div>
<div class="secret-box">🔭 তৃতীয় বছর = মোড়ের বছর: শেষ কোর-জোড়া + প্রথম রিসার্চ-জোড়া = ৩৬ ক্রেডিট; প্রতি অ্যাসাইনমেন্টে এক নিজের-প্রশ্ন, প্রতি সপ্তাহে এক প্রশ্ন-বাগান-বিকাল, এবং বছর শেষে একটি স্থায়ী কমিটি-কাঠামো।</div>`,
  senior: {
    title: "Year 3 জীবন্ত চেকলিস্ট (Fall 2028 – Summer 2029)",
    body: `<p><strong>শুরুতে:</strong> 'প্রশ্ন-বীজ' নোটফাইল খোলো — DIT 7083/6053-এর প্রতিটি অ্যাসাইনমেন্টে যে নিজের-প্রশ্ন লুকালে, বছর শেষে ১০+ বীজ জমা থাকবে। <strong>মাঝে:</strong> RSH-জোড়ার সময় প্রতিটি পদ্ধতি-আলোচনায় নিজের LedgerPilot-ডেটা মনে মেলাও; কমিটি-প্রার্থীদের লিস্ট (৩-৫ নাম) + office-hour সফর। <strong>শেষে:</strong> ৩৬ ক্রেডিট + কমিটি-চূড়ান্ত (chair + ২ সদস্য) + প্রশ্ন-বীজের ফাইল থেকে ২-৩টি 'বড় প্রশ্ন'-এ নেমে আসা। <strong>সংকট-সংকেত:</strong> কোনো প্রফেসরের সাথে কথা বলে আত্মবিশ্বাস কমে গেলে সেই কমিটি-নয়; ভালো চেয়ার তোমার প্রশ্ন বড় করে, ছোট নয়।</p>`
  }
});
// ── দরজা ২২ · চুক্তির দশক (Year 4: Fall 2029 – Summer 2030) ──────────────────
doors.push({
  num: 22,
  icon: "📜",
  color: "#5eead4",
  name: "চুক্তির দশক",
  subtitle: "The Decade of the Contract — Proposal & IRB (Fall 2029 – Summer 2030)",
  tech: "RSH 8023 (Design) + RSH 8033 (Adv. Methodology) + DIT 9006 (Proposal Prep, 6cr) (12 credits) · IRB if human-subjects",
  spirit: "إِنَّ اللَّهَ يَأْمُرُكُمْ أَن تُؤَدُّوا الْأَمَانَاتِ إِلَى أَهْلِهَا — 'আল্লাহ আদেশ দেন আমানত তার হকদারকে বুঝিয়ে দিতে' (কুরআন ৪:৫৮); চুক্তি-বছরের শপথ — যা কথা দিলে, লিখিতে দাও",
  secret: "চতুর্থ বছরের এক কথা: <strong>প্রস্তাবনা হলো চুক্তি</strong>। তুমি কমিটির কাছে লিখিত প্রতিশ্রুতি দিচ্ছ — 'এই প্রশ্ন, এই পদ্ধতি, এই সময়ে, এই ফল'। যে প্রস্তাবনা এই চুক্তি-চেতনায় লেখা, ডিফেন্স-দিনে তার মালিক শান্ত; যে অলংকার-ভরা কিন্তু চুক্তি-শূন্য, সে কাগজ সাজানো বালির তৈরি।",
  recall: {
    q: "Year 4-এর ৩টি কোর্স কী কী, আর IRB কখন?",
    qen: "Year 4's three courses, and when is IRB?",
    a: "Fall 2029: RSH 8023 (Design — স্থপতির প্রাসাদ) + RSH 8033 (Adv. Methodology — গবেষণার তাঁত); Spring 2030: DIT 9006 (Proposal Prep, 6cr — কারিগরখানা)। IRB (human-subjects হলে) Spring-এর শেষ/Summer-এর শুরুতে জমা — তাহলে Year 5-এর শুরুতে ডেটা-সংগ্রহের অনুমতি হাতে।",
    aen: "Fall 2029: RSH 8023 (Design) + RSH 8033 (Adv. Methodology); Spring 2030: DIT 9006 (Proposal Prep, 6cr). IRB (if human-subjects) submitted late Spring / early Summer — so Year 5 opens with data-collection permission in hand."
  },
  story: `<p class="scene-setting">২০২৯-এর শরৎ। কাফেলা এখন পাহাড়ের কোলে — পেছনে ৩৬ ক্রেডিট, সামনে প্রস্তাবনার শহর। এই দরজার মাস্টার <strong>চুক্তিকার ইমামউদ্দিন</strong> — মরু-বাণিজ্যের যুগের লোক, যার কলমে হাজার চুক্তি লেখা, যে জানে প্রতিটি বাক্য পরে কী দাঁড়ায়। তিনি বলেন, "শুনো মুসাফির — প্রস্তাবনা প্রদর্শনী নয়, <strong>চুক্তি</strong>। তুমি লিখছ: আমি এই গ্যাপ দেখিয়েছি (সমস্যা), এই পদ্ধতিতে মাপব (নকশা), এই মানে সফল বলব (ফলাফল-মানদণ্ড), এই সময়ে শেষ করব (সময়রেখা)। কমিটি যখন সই করবে, তুমি বাঁধা পড়লে — আর সেটাই ভালো: চুক্তি-বাঁধা ডিসার্টেশন দ্রুত শেষ হয়, কারণ 'আরেকটু কি করা যায়' রোগ থেকে বাঁচায়। তোমার RSH-জোড়া (6023, 6033) শরতে প্রাসাদ-তাঁত শেষ করো; Spring-এ DIT 9006-তে প্রস্তাবনার খসড়া তিন-পর্বে: <strong>অধ্যায়-১ খসড়া → কমিটি-রিভিউ → সংশোধিত পূর্ণ প্রস্তাবনা</strong>। আর যদি তোমার গবেষণা মানুষ-নিয়ে (ইন্টারভিউ, সার্ভে) — Summer শুরুর আগেই IRB-নথি জমা; অনুমতি ছাড়া একটি ইন্টারভিউও নয়।"</p>
<p class="scene-setting en">Autumn 2029. The caravan rests at the mountain's foot — 36 credits behind, the city of the proposal ahead. This door's master is <strong>Imamuddin the Contract-Writer</strong> — a man of the desert-trade era whose pen has written a thousand contracts and who knows what every sentence becomes later. He says, "Listen, traveler — a proposal is not an exhibition, it is a <strong>contract</strong>. You are writing: I have shown this gap (problem), I will measure by this method (design), by this standard I will call it success (criteria), by this date I will finish (timeline). When the committee signs, you are bound — and that is good: a contract-bound dissertation finishes faster, because it saves you from the disease of 'couldn't I also...'. Finish the palace and the loom (RSH 8023, 6033) in autumn; in Spring draft the DIT 9006 proposal in three passes: <strong>Chapter-1 draft → committee review → revised full proposal</strong>. And if your research touches people (interviews, surveys) — submit IRB before Summer begins; not one interview without permission."</p>
<div class="dialogue"><strong>তুমি:</strong> ইমামউদ্দিন-সাহেব, প্রস্তাবনা কত পৃষ্ঠা হওয়া চাই?<br><strong>চুক্তিকার ইমামউদ্দিন:</strong> ভুল প্রশ্ন! চুক্তির মাপ পৃষ্ঠায় নয়, <strong>ধারায়</strong>। পাঁচটি ধারা থাকলেই চুক্তি পূর্ণ: (১) সমস্যা ও গ্যাপ-দর্শন; (২) প্রশ্ন বা অনুমান; (৩) পদ্ধতি ও নকশা; (৪) ফলাফল-মানদণ্ড; (৫) সময়রেখা। এর বাইরে যা লেখো, সেটা অলংকার — সুন্দর, কিন্তু চুক্তির অংশ নয়। মনে রেখো: কমিটি তোমার ভাষার জ্যান্ত খোঁজে, মৃত শব্দের স্তূপ নয়।<br><strong>তুমি:</strong> আর যদি কমিটি বড় ধরনের বদল চায়?<br><strong>ইমামউদ্দিন:</strong> তাহলে বুঝবে চুক্তি এখনো পাকেনি। রাগ কোরো না — তারা তোমার চুক্তির সাক্ষী, ভবিষ্যতের ডিফেন্সেও তারাই দাঁড়াবে। প্রতিটি মন্তব্যের লিখিত জবাব-তালিকা বানাও ('মন্তব্য → কী করলাম → কোথায় বদলাল'); এই জবাব-নথিই সংশোধনী-প্রক্রিয়ার মেরুদণ্ড।</div>
<div class="dialogue en"><strong>You:</strong> Imamuddin, how many pages should the proposal be?<br><strong>Imamuddin:</strong> Wrong question! A contract is measured not in pages but in <strong>clauses</strong>. Five clauses make it whole: (1) problem and gap; (2) questions or hypotheses; (3) method and design; (4) success criteria; (5) timeline. Whatever you write beyond these is ornament — beautiful, but not contract. Remember: the committee seeks your living voice, not heaps of dead words.<br><strong>You:</strong> And if the committee demands big changes?<br><strong>Imamuddin:</strong> Then the contract is not ripe. Don't be angry — they are witnesses to your contract, and at your future defense they will stand there again. Make a written response-list for every comment ('comment → what I did → where it changed'); that response-document is the spine of the revision process.</div>
<table class="kv-table">
<tr><th>চতুর্থ বছরের ঋতু</th><th>কাজ</th><th>ক্রেডিট-জমা</th></tr>
<tr><td class="hl">Fall 2029</td><td>RSH 8023 (D15) + RSH 8033 (D16) — প্রাসাদ ও তাঁত; প্রশ্ন-বীজ থেকে বড়-প্রশ্নে নেমে আসা</td><td>৪২</td></tr>
<tr><td class="hl">Spring 2030</td><td>DIT 9006 (D17) — প্রস্তাবনার তিন-পর্ব খসড়া; কমিটি-রিভিউ চক্র</td><td>৪৮</td></tr>
<tr><td class="hl">Summer 2030</td><td>IRB-জমা (human-subjects হলে) + সংশোধনী; অনুমতির অপেক্ষা = সাহিত্য-পাঠের সময়</td><td>৪৮</td></tr>
</table>
<div class="callout warn"><span class="co-icon">⚠️</span><div><strong>চতুর্থ-বছরের ফাঁদ:</strong> (১) 'আরেকটু ভালো প্রশ্ন' রোগ — প্রস্তাবনা-বছরে অনন্ত-উন্নয়ন মানেই অনন্ত-বিলম্ব; চুক্তি-ধারা পাঁচটা দাঁড়ালে জমা দাও; (২) IRB-কে শেষ-মুহূর্তের কাগজ ভাবা — রিভিউয়ে সপ্তাহ লাগে, সংশোধনী চাইলে আরও; Summer-এ জমা না হলে Year 5-এর ডেটা-সংগ্রহ পিছায়; (৩) কমিটি-মন্তব্যকে আক্রমণ ভাবা — প্রতিটি মন্তব্য ডিফেন্স-দিনের পূর্বাভাস-প্রশ্ন; এখনই শুধরে নেওয়া সস্তা।</div></div>
<div class="callout tip"><span class="co-icon">🔗</span><div><strong>রিহলা-সেতু:</strong> দরজা ১৫-১৬ (Design, Methodology) শরৎ-পাঠ; দরজা ১৭ (কারিগরখানা) বসন্ত-পাঠ; Book 19 (Researcher's Compass) চুক্তি-ধারা লেখার সঙ্গী; Book 34 (Citation Integrity) প্রস্তাবনার রেফারেন্স-প্রহরী।</div></div>
<div class="verse">يَا أَيُّهَا الَّذِينَ آمَنُوا أَوْفُوا بِالْعُقُودِ — "হে ঈমানদারগণ, চুক্তি পূর্ণ করো।" (কুরআন ৫:১) — প্রস্তাবনা যে-চুক্তি, তা নিজের ওপর পূর্ণ করাই ডিসার্টেশন।</div>
<div class="secret-box">📜 চতুর্থ বছর = চুক্তি-বছর: প্রাসাদ+তাঁত+কারিগরখানা = ৪৮ ক্রেডিট; পাঁচ-ধারার প্রস্তাবনা, তিন-পর্বের খসড়া, লিখিত জবাব-তালিকা, Summer-এ IRB।</div>`,
  senior: {
    title: "Year 4 জীবন্ত চেকলিস্ট (Fall 2029 – Summer 2030)",
    body: `<p><strong>শুরুতে:</strong> প্রশ্ন-বীজ-ফাইল থেকে <strong>একটি</strong> বড় প্রশ্ন বেছে নাও — দুই-তিনটি নয়; চুক্তি এক-প্রশ্নের হয়। <strong>মাঝে:</strong> DIT 9006-চলাকালে প্রতি দুই সপ্তাহে চেয়ারের সাথে ৩০-মিনিটের ফলো-আপ; খসড়া-অংশ ছোট ছোট পাঠাও, পুরো অধ্যায় জমা দেওয়ার আগে। <strong>শেষে:</strong> ৪৮ ক্রেডিট + কমিটি-সইকৃত প্রস্তাবনা + (human-subjects হলে) IRB-জমা। <strong>সংকট-সংকেত:</strong> প্রস্তাবনার ভাষা প্রতিটি সংশোধনে সম্পূর্ণ নতুন হয়ে যাচ্ছে → তুমি চুক্তি লিখছ না, প্রদর্শনী সাজাচ্ছ; পাঁচ-ধারা কাঠামোয় ফিরে যাও।</p>`
  }
});
// ── দরজা ২৩ · সম্মিলন-মজলিস ও প্রত্যাবর্তন (Year 5: Fall 2030 – 2031) ──────────────────
doors.push({
  num: 23,
  icon: "🎓",
  color: "#5eead4",
  name: "সম্মিলন-মজলিস ও প্রত্যাবর্তন",
  subtitle: "The Assembly & The Return — Dissertation, Defense, Doctor (Fall 2030 – 2031)",
  tech: "DIT 9016 (Applied Research Project I) + DIT 9026 (Applied Research Project II) (12 credits) · Data Collection → Findings → Writing → Defense · 6 Program Outcomes",
  spirit: "وَأَن لَّيْسَ لِلْإِنسَانِ إِلَّا مَا سَعَى — 'মানুষের জন্য তা-ই ছাড়া কিছু নেই, সে যা চেষ্টা করে' (কুরআন ৫৩:৩৯); শেষ বছরের বিদায়-নীতি — সারা-রিহলার সওয়াব তোমার সাধনায়ই",
  secret: "পঞ্চম বছর দৌড়ের বছর নয় — <strong>প্রত্যাবর্তনের</strong> বছর। ইবনে বতুতা ২৯ বছরের সফর শেষে ফেরেননি একা — ফিরেছেন সাথে করে <strong>রিহলা</strong> নিয়ে, যা পরের মুসাফিরদের পথ দেখায়। তোমার ডিসার্টেশন তাই শুধু ডিগ্রি-নথি নয় — তোমার ৬০-ক্রেডিট রিহলার সাক্ষ্যপত্র; আর ডিফেন্স-দিনের প্রশ্ন 'তুমি কী জানলে?' নয় — 'পরের মুসাফির তোমার কাছ থেকে কী পাবে?'",
  recall: {
    q: "Year 5-এর তিন পর্ব ও ডিফেন্সের আসল প্রশ্ন কী?",
    qen: "Year 5's three phases, and defense's real question?",
    a: "পর্ব-১ (Fall 2030): DIT 9016 — IRB-অনুমতিতে ডেটা-সংগ্রহ + বিশ্লেষণ + অধ্যায়-খসড়া; পর্ব-২ (Spring 2031): DIT 9026 — পূর্ণ খসড়া + কমিটি-সই + ডিফেন্স-প্রস্তুতি; পর্ব-৩: ডিফেন্স → চূড়ান্ত সংশোধনী → 'ডক্টর'। আসল প্রশ্ন: 'তোমার অবদান (contribution) কী — জ্ঞানের দেহে তুমি নতুন কী যোগ করলে?'",
    aen: "Phase 1 (Fall 2030): DIT 9016 — IRB-approved data collection + analysis + chapter drafts; Phase 2 (Spring 2031): DIT 9026 — full draft + committee sign-off + defense prep; Phase 3: defense → final revisions → 'Doctor.' The real question: 'What is your contribution — what new thing did you add to the body of knowledge?'"
  },
  story: `<p class="scene-setting">২০৩০-এর শরৎ। পেছনে ৪৮ ক্রেডিট আর সই-করা চুক্তি; সামনে শেষ বারোই মাস। এই শেষ দরজার মাস্টার কেউ অন্য নয় — <strong>ফিরে-আসা মুসাফির স্বয়ং</strong>: ৩০ বছর আগে এই পথ দিয়ে ডক্টরেট করা এক বৃদ্ধ, যার হাতে পুরনো চামড়ার ব্যাগ, কাঁধে শিক্ষকতার চাদর। তিনি বলেন, "আমি তোমার শেষ দরজার দারওয়ান। তিনটি কথা দিয়ে যাই। <strong>প্রথম:</strong> ডেটা-সংগ্রহ চুক্তির সীমায় থাকুক — IRB-র প্রতিটি শর্ত মানুষের আমানত; একটি ইন্টারভিউ বাড়তি হলেও অনুমতি নাও। <strong>দ্বিতীয়:</strong> লেখা হবে সাপ্তাহিক-ব্যাচে, অনুপ্রেরণায় নয় — প্রতি শুক্রবার চেয়ারের কাছে এক 'চাঙ্ক' (১-২ পৃষ্ঠা) পাঠাও; ছোট নিয়মিত পাঠ বড় বিরল পাঠকে হারায়। <strong>তৃতীয়:</strong> ডিফেন্স ভয়ের নয়, <strong>মজলিসের</strong> — সেদিন ঘরের সবাই প্রশ্ন করবে যারা তোমার চুক্তির সাক্ষী; প্রতিটি প্রশ্নের জবাব তুমি চার বছর ধরেই তৈরি করেছ। আর যখন কমিটি-চেয়ার বলবেন 'অভিনন্দন, ডক্টর' — সেই শব্দটা শুধু তোমার নয়; পথে যাদের দরজায় দরজায় ঠাঁই পেয়েছ, সালেহ-জুবায়ের-আয়েশা-ইমামউদ্দিনের, পরিবারের, আর যে-শিক্ষক আজও তোমার ভেতরে কথা বলেন।"</p>
<p class="scene-setting en">Autumn 2030. Behind you: 48 credits and a signed contract; ahead: the final twelve months. The master of this last door is no one else — <strong>the Returned Traveler himself</strong>: an elder who took this road to a doctorate thirty years ago, an old leather bag in hand, a teacher's shawl on his shoulder. He says, "I am the doorkeeper of your final door. I leave you three words. <strong>First:</strong> let data collection stay within the contract's bounds — every IRB condition is a human trust; even one extra interview needs permission. <strong>Second:</strong> writing happens in weekly batches, not inspiration — every Friday send the chair one 'chunk' (1-2 pages); small regular deliveries beat large rare ones. <strong>Third:</strong> the defense is not a terror, it is an <strong>assembly</strong> — everyone in the room asking questions is a witness to your contract; you have been preparing the answer to each for four years. And when the committee chair says 'Congratulations, Doctor' — that word belongs not to you alone; to every master at whose door you found shelter — Salih, Zubayr, Ayesha, Imamuddin — to your family, and to the teacher who still speaks inside you."</p>
<div class="dialogue"><strong>তুমি:</strong> মাস্টার, শেষ বছরের সবচেয়ে বড় শত্রু কে?<br><strong>ফিরে-আসা মুসাফির:</strong> শত্রু বলো বা পরীক্ষা — তিনটি। <strong>নিখাত:</strong> লেখার শেষ অধ্যায়ে 'আর একটু' করতে করতে মাস গড়িয়ে যাওয়া — ওষুধ চুক্তি-সময়রেখা; তারিখ লেখা থাকে, অনুভূতি নয়। <strong>একাকিত্ব:</strong> সহপাঠীরা কেউ কোর্সে নেই, কাজের দল গবেষণা বোঝে না, পরিবার ক্লান্ত — ওষুধ মাসিক 'রিহলা-চেকপয়েন্ট' কথা (চেয়ার + এক বন্ধু + পরিবারের একজন)। <strong>ভবিষ্যতের-লোভ:</strong> 'ডিফেন্সের পর কী করব' ভেবে বর্তমান অধ্যায় ফেলে রাখা — ওষুধ: পরের-চাঙ্ক-শুধু; ভবিষ্যতের খাতা আলাদা, শুক্রবারের চাঙ্ক আগে।<br><strong>তুমি:</strong> আর ৬টি program-outcome?<br><strong>ফিরে-আসা মুসাফির:</strong> ডিফেন্সের আগে নিজের টেবিলে সাজিয়ে রাখো ছয় প্রশ্ন: কোর্স-জ্ঞান, গবেষণা-দক্ষতা, নেতৃত্ব-দৃষ্টি, প্রযুক্তি-সমাধান, নৈতিক-চেতনা, যোগাযোগ — তোমার ডিসার্টেশনের কোন অধ্যায়-কোন ফল কোন outcome-এর প্রমাণ। এই ম্যাপিং-টেবিল ডিফেন্সে তোমার ঢাল।</div>
<div class="dialogue en"><strong>You:</strong> Master, what is the final year's greatest enemy?<br><strong>The Returned Traveler:</strong> Call them enemies or trials — three. <strong>Boredom-exhaustion:</strong> 'just a bit more' stretching months in the last chapter — the cure is the contract timeline; dates are written, not feelings. <strong>Loneliness:</strong> no classmates in courses, the work team doesn't understand research, family is tired — the cure is a monthly 'rihla checkpoint' talk (chair + one friend + one family member). <strong>Future-greed:</strong> daydreaming 'after the defense' while the current chapter sits — cure: next-chunk-only; a separate notebook for the future, the Friday chunk first.<br><strong>You:</strong> And the six program outcomes?<br><strong>The Traveler:</strong> Before the defense, lay six questions on your own table: course knowledge, research skill, leadership vision, technological solution, ethical awareness, communication — which chapter, which finding of your dissertation proves which outcome. That mapping-table is your shield at the defense.</div>
<table class="kv-table">
<tr><th>পঞ্চম বছরের পর্ব</th><th>কাজ</th><th>ক্রেডিট-জমা</th></tr>
<tr><td class="hl">Fall 2030</td><td>DIT 9016 (D18) — ডেটা-সংগ্রহ + বিশ্লেষণ; অধ্যায় ৪-এর খসড়া; সাপ্তাহিক চাঙ্ক-চক্র চালু</td><td>৫৪</td></tr>
<tr><td class="hl">Spring 2031</td><td>DIT 9026 — পূর্ণ খসড়া → কমিটি-সই → ডিফেন্স; ৬-outcome ম্যাপিং-টেবিল</td><td>৬০ ✓</td></tr>
<tr><td class="hl">2031 (ডিফেন্স-পর্ব)</td><td>মজলিস-দিন → চূড়ান্ত সংশোধনী → ডিগ্রি-নথি → <strong>প্রত্যাবর্তন: তুমি এখন পরের মুসাফিরদের দরজা-দারওয়ান</strong></td><td>৬০</td></tr>
</table>
<div class="callout warn"><span class="co-icon">⚠️</span><div><strong>শেষ-বছরের ফাঁদ:</strong> (১) 'পারফেক্ট অধ্যায়' অন্বেষণ — সম্পূর্ণ-পাণ্ডুলিপি জমা দেওয়ার পরেই চমৎকার হয়, আগে নয়; খসড়া-ই কাজের জিনিস; (২) ডিফেন্স-দিনের উত্তর সেদিনই বানানো — কমিটি-রিভিউয়ের প্রতিটি প্রশ্নই ছিল পূর্বাভাস; পুরনো জবাব-নথি হাতের কাছে রাখো; (৩) ডিগ্রির পরে 'এখন বিশ্রাম' — বরং রিহলা লেখো: তোমার থিসিস-গল্প, কোন দরজায় কী শিখলে — পরের মুসাফিরের জন্য; এটাই জ্ঞানের আমানত ফেরত দেওয়া।</div></div>
<div class="callout tip"><span class="co-icon">🔗</span><div><strong>রিহলা-সেতু:</strong> দরজা ১৭-১৮ (কারিগরখানা, সম্মিলন-মজলিস) এই বছরের পাঠ; Book 34 (Citation Integrity) চূড়ান্ত পাণ্ডুলিপির প্রহরী; Book 20 (Graduate Ascent) — ডিফেন্সের পরের জীবনের মানচিত্র। আর মনে রেখো: পুরো রিহলাটা ২০২৬-এ শুরু হয়েছিল একটাই সিদ্ধান্তে — 'আমি যাব।'</div></div>
<div class="verse">وَالْعَصْرِ ۝ إِنَّ الْإِنسَانَ لَفِي خُسْرٍ ۝ إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ — "সময়ের কসম — মানুষ ক্ষতিতেই, তবে যারা ঈমান রাখে, সৎকাজ করে, পরস্পরকে সত্যের উপদেশ দেয় ও ধৈর্যের উপদেশ দেয়।" (কুরআন ১০৩:১-৩) — পাঁচ বছরের রিহলার সার-সূত্র: ঈমান + কাজ + সত্য-কথা + ধৈর্য।</div>
<div class="secret-box">🎓 পঞ্চম বছর = প্রত্যাবর্তনের বছর: ৬০ ক্রেডিট ✓, ডিফেন্স = মজলিস (শত্রু নয়), শুক্রবার-চাঙ্ক, ৬-outcome ঢাল, এবং শেষ কাজ — পরের মুসাফিরের জন্য তোমার রিহলা-নথি। ২০২৬-এ যে ছাত্রটি 'আমি যাব' বলেছিল, ২০৩১-এ সে-ই ডাকে 'ডক্টর সাহেব'।</div>`,
  senior: {
    title: "Year 5 জীবন্ত চেকলিস্ট (Fall 2030 – 2031)",
    body: `<p><strong>শুরুতে:</strong> (human-subjects হলে) IRB-অনুমতি হাতে; সাপ্তাহিক শুক্র-চাঙ্ক চুক্তি চেয়ারের সাথে চালু; লেখার সময়সূচি ক্যালেন্ডারে ব্লক-বাঁধা। <strong>মাঝে:</strong> অধ্যায়-ক্রম নম্বর দিয়ে অগ্রগতি ট্র্যাক (৪=বিশ্লেষণ, ৫=আলোচনা সবচেয়ে ধীর — জন্য বেশি সময়); মাসিক রিহলা-চেকপয়েন্ট কথা বাদ দিও না। <strong>শেষে:</strong> কমিটি-সই → ডিফেন্স-তারিখ → উপস্থাপনা-রান-থ্রু (কমপক্ষে ৩ বার, একবার বাইরের মানুষের সামনে) → ডিফেন্স → চূড়ান্ত সংশোধনী → <strong>ডক্টরেট</strong>। <strong>সংকট-সংকেত:</strong> একই অনুচ্ছেদ তিন সপ্তাহ ধরে ঘষছ → পাঠ-রোধ (writer's block) নয়, সিদ্ধান্ত-রোধ; চেয়ারের সাথে ১৫ মিনিটে সিদ্ধান্তগুলো ভাঙো — লেখা নিজে নিজেই আসবে।</p>`
  }
});
// END-DOORS-19-23
